<?php

return [
    'title' => 'Export',
    'with_header' => 'Letterhead',
    'with_footer' => 'Footer',
    'with_date' => 'Generated date',
    'with_user' => 'Generated by',
    'generated_on' => 'Generated on :date',
    'generated_by' => 'by :name',
    'download_pdf' => 'Download PDF',
    'download_excel' => 'Download Excel',
    'print' => 'Print',
    'no_records' => 'No records to export.',
];
